name: todo_hive_example
description: Very simple todo app made with Hive.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2


dev_dependencies:
#  flutter_test:
#    sdk: flutter
  hive_generator: ^0.7.0+2
  build_runner: ^1.8.1



flutter:

  uses-material-design: true
